### ISSUE TITLE
Can't locate object method "register_component"

### ISSUE THREAD

**Issue by tlhackque** [kentnl/Dist-Zilla-Plugin-MetaProvides#4]
````
 dzil build
Can't locate object method "register_component" via package "Dist::Zilla::Plugin::MetaProvides" at /usr/lib/perl5/site_perl/5.8.8/Dist/Zilla/MVP/Section.pm line 39, <GEN0> line 47.
````
Tried both release and devel release version of Dist::Zilla::Plugin::MetaProvides

Dist::Zilla 5.043 (latest)

If I comment out [MetaProvides], build succeeds.

Relevant portions of dist.ini:
```ini
[MetaConfig]

[MetaProvides]

[MetaResources]
repository.url = https://github.com...
[MinimumPerl]
perl = 5.008008

[MetaYAML]
[MetaJSON]
```

**Comment by kentfredric** [comment]
`[MetaProvides]` Does nothing on its own, and is merely a namespace holder at this point.

You want either `[MetaProvides::Package]` or `[MetaProvides::Class]`, etc. 

So this "error" is intentional. 

https://metacpan.org/pod/Dist::Zilla::Plugin::MetaProvides#SYNOPSIS

```ini
[MetaProvides::Class]
inherit_version = 0    ;optional flag
inherit_missing = 0    ;optional flag
meta_noindex    = 1    ;optional flag
 
[MetaProvides::Package]
inherit_version = 0    ;optional flag
inherit_missing = 0    ;optional flag
meta_noindex    = 1    ;optional flag
 
[MetaProvides::FromFile]
inherit_version = 0     ;optional flag
inherit_missing = 0     ;optional flag
file = some_file.ini    ;mandatory flag
reader_name = Config::INI::Reader ;optional flag
meta_noindex    = 1     ;optional and useless flag
```

**Comment by kentfredric** [comment]
I can however add a register_component stub that dies with a more explicit error so you know what's wrong.

**Comment by tlhackque** [comment]
Thanks for the quick response.

That would be helpful.  I didn't get that from the synopsis, and I didn't think I was having a particularly opaque day...

A couple of sentences in the synopsis would help, something like:

[MetaProvides] should not appear in your dist.ini since MetaProvides is the parent of plugins that do the work..  

If you want to include metadata about the packages that your distribution provides, use [MetaProvides::Package].

If you want to include metadata about the Classes that your distribution provides, use [MetaProvides::Class]
